name: OSX
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -e -l {0}
jobs:
  build:
    runs-on: macos-${{ matrix.os }}
    name: macos-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - 13
        - 14
        - 15

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment-dev.yml
        cache-environment: true

    - name: Configure using CMake
      run: cmake -G Ninja -Bbuild -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DPYTHON_EXECUTABLE=`which python` -DDOWNLOAD_GTEST=ON $(Build.SourcesDirectory)

    - name: Install
      working-directory: build
      run: cmake --install .

    - name: Build
      working-directory: build
      run: cmake --build . --target test_xtensor_python_pybind11 test_xtensor_python_nanobind --parallel 8

    - name: Run tests (C++ pybind11)
      working-directory: build/test
      run: ./test_xtensor_python_pybind11

    - name: Run tests (C++ nanobind)
      working-directory: build/test
      run: ./test_xtensor_python_nanobind

    - name: Run tests (Python)
      run: pytest -s

    - name: Run benchmarks (pybind11 vs nanobind)
      working-directory: benchmark
      run: |
        python run_benchmarks.py --iterations 100 --size 100000

    - name: Example - readme 1
      working-directory: docs/source/examples/readme_example_1
      run: |
        cmake -Bbuild -DPython_EXECUTABLE=`which python`
        cd build
        cmake --build .
        cp ../example.py .
        python example.py

    - name: Example - copy \'cast\'
      working-directory: docs/source/examples/copy_cast
      run: |
        cmake -Bbuild -DPython_EXECUTABLE=`which python`
        cd build
        cmake --build .
        cp ../example.py .
        python example.py

    - name: Example - SFINAE
      working-directory: docs/source/examples/sfinae
      run: |
        cmake -Bbuild -DPython_EXECUTABLE=`which python`
        cd build
        cmake --build .
        cp ../example.py .
        python example.py
